// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=Iterative_a74b613985
ROOST_METHOD_SIG_HASH=Iterative_40eb14d923

FUNCTION_DEF=func Iterative(a, b int64) int64 // Iterative Faster iterative version of GcdRecursive without holding up too much of the stack

Scenario 1: Testing with positive integers

Details:
  Description: This test is meant to check the functionality of the Iterative function when provided with positive integers. The function should return the greatest common divisor of the two numbers.
Execution:
  Arrange: No setup is required as the function takes two integers as input.
  Act: Invoke the Iterative function with two positive integers.
  Assert: Use Go testing facilities to verify that the actual results match the expected outcomes.
Validation:
  The choice of assertion is based on the mathematical fact that the greatest common divisor of two numbers does not change regardless of the order in which they are presented. The importance of this test is to ensure that the function works correctly with positive integers.

Scenario 2: Testing with negative integers

Details:
  Description: This test is meant to check the functionality of the Iterative function when provided with negative integers. The function should return the greatest common divisor of the two numbers.
Execution:
  Arrange: No setup is required as the function takes two integers as input.
  Act: Invoke the Iterative function with two negative integers.
  Assert: Use Go testing facilities to verify that the actual results match the expected outcomes.
Validation:
  The choice of assertion is based on the mathematical fact that the greatest common divisor of two numbers does not change regardless of the sign of the numbers. The importance of this test is to ensure that the function works correctly with negative integers.

Scenario 3: Testing with zero

Details:
  Description: This test is meant to check the functionality of the Iterative function when one of the numbers is zero. The function should return the non-zero number as the greatest common divisor.
Execution:
  Arrange: No setup is required as the function takes two integers as input.
  Act: Invoke the Iterative function with one number as zero and the other as a non-zero number.
  Assert: Use Go testing facilities to verify that the actual results match the expected outcomes.
Validation:
  The choice of assertion is based on the mathematical fact that the greatest common divisor of a number and zero is the number itself. The importance of this test is to ensure that the function works correctly when one of the numbers is zero.

Scenario 4: Testing with both numbers as zero

Details:
  Description: This test is meant to check the functionality of the Iterative function when both numbers are zero. The function should return zero as the greatest common divisor.
Execution:
  Arrange: No setup is required as the function takes two integers as input.
  Act: Invoke the Iterative function with both numbers as zero.
  Assert: Use Go testing facilities to verify that the actual results match the expected outcomes.
Validation:
  The choice of assertion is based on the mathematical fact that the greatest common divisor of zero and zero is zero. The importance of this test is to ensure that the function works correctly when both numbers are zero.
*/

// ********RoostGPT********

package gcd

import "testing"

func TestIterative(t *testing.T) {

	testCases := []struct {
		name     string
		a        int64
		b        int64
		expected int64
	}{
		{
			name:     "Testing with positive integers",
			a:        48,
			b:        18,
			expected: 6,
		},
		{
			name:     "Testing with negative integers",
			a:        -48,
			b:        -18,
			expected: 6,
		},
		{
			name:     "Testing with zero",
			a:        0,
			b:        18,
			expected: 18,
		},
		{
			name:     "Testing with both numbers as zero",
			a:        0,
			b:        0,
			expected: 0,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			result := Iterative(tc.a, tc.b)

			if result != tc.expected {
				t.Errorf("Expected %v, but got %v", tc.expected, result)
			} else {
				t.Logf("Success: Expected %v and got %v", tc.expected, result)
			}
		})
	}
}
