// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test go-samples-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=UnionFind_Union_46455366d6
ROOST_METHOD_SIG_HASH=UnionFind_Union_c67f2fb734

FUNCTION_DEF=func (u UnionFind) Union(a, b int) UnionFind // to merge two sets to which the given elements belong, the Union function serves the purpose

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: \graph\unionfind_test.go
Test Cases:
    [TestUnionFind]

Scenario 1: Union of Two Independent Nodes

Details:
  Description: This scenario is meant to test the functionality of the Union method when merging two nodes that do not have any parent-child relationship. This is the most typical use case for the Union function.

Execution:
  Arrange: Create a UnionFind instance with a certain size and perform the union of two independent nodes.
  Act: Invoke the Union function with the two nodes that have been identified.
  Assert: Verify that the parents of the two nodes are the same after the Union operation.

Validation:
  The assertion confirms that the Union operation accurately updates the parent relationships for the two nodes. This test is crucial to ensure that the function can correctly merge independent sets represented by the nodes.

Scenario 2: Union of Parent and Child Nodes

Details:
  Description: This test scenario validates the Union operation when merging a parent and its direct child. The Union function in this situation should be able to handle this input correctly and avoid creating a circular parent-child relationship.

Execution:
  Arrange: Set up a UnionFind instance, perform a Union operation to create a parent-child relationship between two nodes, and then invoke another Union operation with the same pair of nodes.
  Act: Use the Union function with the created parent and child nodes.
  Assert: Confirm that the parents of the two nodes have not changed after the second Union operation.

Validation:
  The assertion ensures that the Union function can manage parent-child relationships without causing issues like circular dependencies. The validation of this test is critical to assure that the function handles various forms of inputs and maintains the union-find data structure's integrity.

Scenario 3: Union Operation on Non-Existent Nodes

Details:
  Description: This scenario checks the Union function's behavior when trying to merge nodes that do not exist. The function should return the original UnionFind structure without any modifications.

Execution:
  Arrange: Create a UnionFind instance and invoke the Union function with two nodes that are not part of the UnionFind structure.
  Act: Call the Union function with the two non-existant nodes.
  Assert: Verify that the UnionFind structure has not changed after the Union function call.

Validation:
  The assertion validates that the Union operation does not cause any alterations to the UnionFind structure when the nodes do not exist. Testing this scenario is important to ensure that the function adheres to its specifications and robustly handles invalid inputs.
*/

// ********RoostGPT********

package graph

import "testing"

func NewUnionFind(size int) UnionFind {
	parent := make([]int, size)
	sizeArr := make([]int, size)
	for i := range parent {
		sizeArr[i] = 1
		parent[i] = i
	}
	return UnionFind{parent: parent, size: sizeArr}
}
func TestUnion(t *testing.T) {

	testCases := []struct {
		label  string
		size   int
		unions []struct {
			a, b int
		}
		tests []struct{ a, b, expectedParent int }
	}{
		{
			label: "Union of Two Independent Nodes",
			size:  5,
			unions: []struct{ a, b int }{
				{0, 1},
			},
			tests: []struct{ a, b, expectedParent int }{
				{0, 1, 1},
			},
		},
		{
			label: "Union of Parent and Child Nodes",
			size:  5,
			unions: []struct{ a, b int }{
				{0, 1},
				{0, 2},
			},
			tests: []struct{ a, b, expectedParent int }{
				{0, 1, 1},
			},
		},
		{
			label: "Union of non-existing Nodes",
			size:  5,
			unions: []struct{ a, b int }{
				{10, 11},
			},
			tests: []struct{ a, b, expectedParent int }{
				{10, 11, -1},
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.label, func(t *testing.T) {

			u := NewUnionFind(tc.size)
			for _, union := range tc.unions {
				u = u.Union(union.a, union.b)
			}

			for _, test := range tc.tests {
				if parentA := u.Find(test.a); parentA != test.expectedParent {
					t.Errorf("Expected parent of %d to be %d, but got %d", test.a, test.expectedParent, parentA)
				}
				if parentB := u.Find(test.b); parentB != test.expectedParent {
					t.Errorf("Expected parent of %d to be %d, but got %d", test.b, test.expectedParent, parentB)
				}
			}
		})
	}
}
