// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=UnionFind_Find_88d46286a9
ROOST_METHOD_SIG_HASH=UnionFind_Find_a7a54bd30f

FUNCTION_DEF=func (u UnionFind) Find(q int) int // to find the root of the set to which the given element belongs, the Find function serves the purpose

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-samples/graph/unionfind_test.go
Test Cases:
    [TestUnionFind]

Scenario 1: Test Find with single element

Details:
  Description: This test is meant to check the Find function when it is called with a single element. The target scenario is when the UnionFind structure contains only one element.

Execution:
  Arrange: Create a UnionFind structure with one element.
  Act: Invoke the Find function with the single element.
  Assert: Use Go testing facilities to verify that the Find function returns the same element.

Validation:
  The assertion checks if the Find function correctly returns the root of the set, which in this case should be the single element itself. This test is important to ensure that the Find function works correctly for the simplest case.

Scenario 2: Test Find with multiple elements in the same set

Details:
  Description: This test is meant to check the Find function when it is called with multiple elements that belong to the same set. The target scenario is when the UnionFind structure contains multiple elements in the same set.

Execution:
  Arrange: Create a UnionFind structure with multiple elements and perform Union operations to put them in the same set.
  Act: Invoke the Find function with each element.
  Assert: Use Go testing facilities to verify that the Find function returns the same root for all elements.

Validation:
  The assertion checks if the Find function correctly returns the root of the set for all elements in the set. This test is important to ensure that the Find function correctly identifies elements in the same set.

Scenario 3: Test Find with multiple elements in different sets

Details:
  Description: This test is meant to check the Find function when it is called with multiple elements that belong to different sets. The target scenario is when the UnionFind structure contains multiple elements in different sets.

Execution:
  Arrange: Create a UnionFind structure with multiple elements and perform Union operations to put them in different sets.
  Act: Invoke the Find function with each element.
  Assert: Use Go testing facilities to verify that the Find function returns different roots for elements in different sets.

Validation:
  The assertion checks if the Find function correctly returns the root of the set for each element, and that these roots are different for elements in different sets. This test is important to ensure that the Find function correctly identifies elements in different sets.

Scenario 4: Test Find with non-existent element

Details:
  Description: This test is meant to check the Find function when it is called with an element that does not exist in the UnionFind structure. The target scenario is when the UnionFind structure does not contain the given element.

Execution:
  Arrange: Create a UnionFind structure with some elements.
  Act: Invoke the Find function with an element that does not exist in the structure.
  Assert: Use Go testing facilities to verify that the Find function returns an error or a special value indicating that the element does not exist.

Validation:
  The assertion checks if the Find function correctly handles the case when the given element does not exist in the structure. This test is important to ensure that the Find function has proper error handling.
*/

// ********RoostGPT********

package graph

import (
	"errors"
	"testing"
)

func NewUnionFind(n int) *UnionFind {
	parent := make([]int, n)
	size := make([]int, n)
	for i := range parent {
		parent[i] = i
		size[i] = 1
	}
	return &UnionFind{parent: parent, size: size}
}
func TestUnionFind_Find(t *testing.T) {
	tests := []struct {
		name    string
		setup   func() *UnionFind
		element int
		want    int
		wantErr bool
	}{
		{
			name: "Test Find with single element",
			setup: func() *UnionFind {
				u := NewUnionFind(1)
				return u
			},
			element: 0,
			want:    0,
			wantErr: false,
		},
		{
			name: "Test Find with multiple elements in the same set",
			setup: func() *UnionFind {
				u := NewUnionFind(3)
				u.Union(0, 1)
				u.Union(1, 2)
				return u
			},
			element: 1,
			want:    0,
			wantErr: false,
		},
		{
			name: "Test Find with multiple elements in different sets",
			setup: func() *UnionFind {
				u := NewUnionFind(4)
				u.Union(0, 1)
				u.Union(2, 3)
				return u
			},
			element: 2,
			want:    2,
			wantErr: false,
		},
		{
			name: "Test Find with non-existent element",
			setup: func() *UnionFind {
				u := NewUnionFind(2)
				u.Union(0, 1)
				return u
			},
			element: 3,
			want:    -1,
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			u := tt.setup()
			got, err := u.Find(tt.element)
			if (err != nil) != tt.wantErr {
				t.Errorf("UnionFind.Find() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if got != tt.want {
				t.Errorf("UnionFind.Find() = %v, want %v", got, tt.want)
			}
		})
	}
}
func (u *UnionFind) Find(p int) (int, error) {
	if p < 0 || p >= len(u.parent) {
		return -1, errors.New("index is out of range")
	}
	root := p
	for root != u.parent[root] {
		root = u.parent[root]
	}
	return root, nil
}
func (u *UnionFind) Union(p, q int) {
	rootP := u.Find(p)
	rootQ := u.Find(q)
	if rootP == rootQ {
		return
	}
	if u.size[rootP] < u.size[rootQ] {
		u.parent[rootP] = rootQ
		u.size[rootQ] += u.size[rootP]
	} else {
		u.parent[rootQ] = rootP
		u.size[rootP] += u.size[rootQ]
	}
}
