// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=Graph_hasCycleHelper_cb0533a1c6
ROOST_METHOD_SIG_HASH=Graph_hasCycleHelper_7ea66715ac

FUNCTION_DEF=func (g Graph) hasCycleHelper(v int, all, visiting, visited map[int]struct) bool
Scenario 1: Testing with a graph that has no cycle

Details:
  Description: This test is meant to check if the function correctly identifies a graph that does not contain a cycle. The graph is set up such that no cycle exists.

Execution:
  Arrange: Create a Graph object with vertices and edges that do not form a cycle.
  Act: Invoke the hasCycleHelper function with the appropriate parameters.
  Assert: Verify that the function returns false.

Validation:
  The assertion checks if the function correctly identifies that the graph does not contain a cycle. This test is important to ensure that the function can accurately identify graphs without cycles.

Scenario 2: Testing with a graph that has a cycle

Details:
  Description: This test is meant to check if the function correctly identifies a graph that contains a cycle. The graph is set up such that a cycle exists.

Execution:
  Arrange: Create a Graph object with vertices and edges that form a cycle.
  Act: Invoke the hasCycleHelper function with the appropriate parameters.
  Assert: Verify that the function returns true.

Validation:
  The assertion checks if the function correctly identifies that the graph contains a cycle. This test is important to ensure that the function can accurately identify graphs with cycles.

Scenario 3: Testing with an empty graph

Details:
  Description: This test is meant to check if the function correctly handles an empty graph. The graph is set up with no vertices or edges.

Execution:
  Arrange: Create an empty Graph object.
  Act: Invoke the hasCycleHelper function with the appropriate parameters.
  Assert: Verify that the function returns false.

Validation:
  The assertion checks if the function correctly handles an empty graph and returns false, as an empty graph cannot contain a cycle. This test is important to ensure that the function can handle edge cases like an empty graph.

Scenario 4: Testing with a single vertex graph

Details:
  Description: This test is meant to check if the function correctly handles a graph with a single vertex. The graph is set up with one vertex and no edges.

Execution:
  Arrange: Create a Graph object with a single vertex and no edges.
  Act: Invoke the hasCycleHelper function with the appropriate parameters.
  Assert: Verify that the function returns false.

Validation:
  The assertion checks if the function correctly handles a graph with a single vertex and returns false, as a single vertex cannot form a cycle. This test is important to ensure that the function can handle edge cases like a graph with a single vertex.
*/

// ********RoostGPT********

package graph

import "testing"

func TestGraphHasCycleHelper(t *testing.T) {

	testCases := []struct {
		name     string
		graph    Graph
		vertex   int
		expected bool
	}{
		{
			name: "Testing with a graph that has no cycle",
			graph: Graph{
				vertices: 3,
				edges: map[int]map[int]int{
					1: {2: 1},
					2: {3: 1},
					3: {},
				},
				Directed: true,
			},
			vertex:   1,
			expected: false,
		},
		{
			name: "Testing with a graph that has a cycle",
			graph: Graph{
				vertices: 3,
				edges: map[int]map[int]int{
					1: {2: 1},
					2: {3: 1},
					3: {1: 1},
				},
				Directed: true,
			},
			vertex:   1,
			expected: true,
		},
		{
			name: "Testing with an empty graph",
			graph: Graph{
				vertices: 0,
				edges:    map[int]map[int]int{},
				Directed: true,
			},
			vertex:   0,
			expected: false,
		},
		{
			name: "Testing with a single vertex graph",
			graph: Graph{
				vertices: 1,
				edges:    map[int]map[int]int{1: {}},
				Directed: true,
			},
			vertex:   1,
			expected: false,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			all := make(map[int]struct{})
			for i := 1; i <= tc.graph.vertices; i++ {
				all[i] = struct{}{}
			}
			visiting := make(map[int]struct{})
			visited := make(map[int]struct{})

			result := tc.graph.hasCycleHelper(tc.vertex, all, visiting, visited)

			if result != tc.expected {
				t.Errorf("Expected %v, but got %v", tc.expected, result)
			}
		})
	}
}
