// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=Graph_AddWeightedEdge_5dd5f0ac59
ROOST_METHOD_SIG_HASH=Graph_AddWeightedEdge_01b045babe

FUNCTION_DEF=func (g *Graph) AddWeightedEdge(one, two, weight int) // AddWeightedEdge will add a new weighted edge between the provided vertices in the graph

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-samples/graph/bellmanford_test.go
Test Cases:
    [TestBellmanford]

File: go-samples/graph/dijkstra_test.go
Test Cases:
    [TestDijkstra]

File: go-samples/graph/graph_test.go
Test Cases:
    [TestDirectedGraph
    TestUndirectedGraph]

Scenario 1: Add Weighted Edge to Empty Graph

Details:
  Description: This test is meant to check if the function can successfully add a weighted edge to an empty graph. The graph is undirected.

Execution:
  Arrange: Create an empty graph with 2 vertices and set Directed to false.
  Act: Invoke AddWeightedEdge with vertices 1 and 2 and a weight of 10.
  Assert: Check if the edge between vertices 1 and 2 exists and has a weight of 10.

Validation:
  The assertion checks if the edge has been added correctly with the correct weight. This is important as it verifies the basic functionality of the AddWeightedEdge function.

Scenario 2: Add Weighted Edge to Non-Empty Graph

Details:
  Description: This test is meant to check if the function can successfully add a weighted edge to a non-empty graph. The graph is directed.

Execution:
  Arrange: Create a graph with 3 vertices and an edge between vertices 1 and 2 with a weight of 5. Set Directed to true.
  Act: Invoke AddWeightedEdge with vertices 2 and 3 and a weight of 15.
  Assert: Check if the edge between vertices 2 and 3 exists and has a weight of 15.

Validation:
  The assertion checks if the new edge has been added correctly with the correct weight. This is important as it verifies the function's ability to add edges to a graph that already has edges.

Scenario 3: Add Weighted Edge with Negative Weight

Details:
  Description: This test is meant to check if the function can successfully add a weighted edge with a negative weight. The graph is undirected.

Execution:
  Arrange: Create an empty graph with 2 vertices and set Directed to false.
  Act: Invoke AddWeightedEdge with vertices 1 and 2 and a weight of -10.
  Assert: Check if the edge between vertices 1 and 2 exists and has a weight of -10.

Validation:
  The assertion checks if the edge has been added correctly with the correct negative weight. This is important as it verifies the function's ability to handle negative weights.

Scenario 4: Add Weighted Edge to Vertex That Does Not Exist

Details:
  Description: This test is meant to check if the function can successfully add a weighted edge to a vertex that does not exist in the graph. The graph is directed.

Execution:
  Arrange: Create an empty graph with 2 vertices and set Directed to true.
  Act: Invoke AddWeightedEdge with vertices 2 and 3 and a weight of 10.
  Assert: Check if the edge between vertices 2 and 3 exists and has a weight of 10.

Validation:
  The assertion checks if the edge has been added correctly with the correct weight, even though one of the vertices did not exist in the graph before the function call. This is important as it verifies the function's ability to handle vertices that do not exist in the graph.
*/

// ********RoostGPT********

package graph

import "testing"

func TestAddWeightedEdge(t *testing.T) {
	testCases := []struct {
		name     string
		vertices int
		edges    []Edge
		newEdge  Edge
		directed bool
	}{
		{
			name:     "Add Weighted Edge to Empty Graph",
			vertices: 2,
			edges:    []Edge{},
			newEdge:  Edge{Start: 1, End: 2, Weight: 10},
			directed: false,
		},
		{
			name:     "Add Weighted Edge to Non-Empty Graph",
			vertices: 3,
			edges:    []Edge{{Start: 1, End: 2, Weight: 5}},
			newEdge:  Edge{Start: 2, End: 3, Weight: 15},
			directed: true,
		},
		{
			name:     "Add Weighted Edge with Negative Weight",
			vertices: 2,
			edges:    []Edge{},
			newEdge:  Edge{Start: 1, End: 2, Weight: -10},
			directed: false,
		},
		{
			name:     "Add Weighted Edge to Vertex That Does Not Exist",
			vertices: 2,
			edges:    []Edge{},
			newEdge:  Edge{Start: 2, End: 3, Weight: 10},
			directed: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			g := &Graph{
				vertices: tc.vertices,
				edges:    make(map[int]map[int]int),
				Directed: tc.directed,
			}

			for _, edge := range tc.edges {
				g.AddWeightedEdge(int(edge.Start), int(edge.End), edge.Weight)
			}

			g.AddWeightedEdge(int(tc.newEdge.Start), int(tc.newEdge.End), tc.newEdge.Weight)

			if weight, ok := g.edges[int(tc.newEdge.Start)][int(tc.newEdge.End)]; !ok || weight != tc.newEdge.Weight {
				t.Errorf("Failed to add edge from %d to %d with weight %d", tc.newEdge.Start, tc.newEdge.End, tc.newEdge.Weight)
			}

			if !tc.directed {
				if weight, ok := g.edges[int(tc.newEdge.End)][int(tc.newEdge.Start)]; !ok || weight != tc.newEdge.Weight {
					t.Errorf("Failed to add edge from %d to %d with weight %d", tc.newEdge.End, tc.newEdge.Start, tc.newEdge.Weight)
				}
			}
		})
	}
}
