// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=UnionFind_Union_46455366d6
ROOST_METHOD_SIG_HASH=UnionFind_Union_c67f2fb734

FUNCTION_DEF=func (u UnionFind) Union(a, b int) UnionFind // to merge two sets to which the given elements belong, the Union function serves the purpose

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-samples/graph/unionfind_test.go
Test Cases:
    [TestUnionFind]

Scenario 1: Union of two distinct elements

Details:
    Description: This test is meant to check the functionality of the Union operation when two distinct elements are passed. The function should be able to merge the sets containing these two elements.
Execution:
    Arrange: Initialize a UnionFind struct with a certain number of elements.
    Act: Call the Union function on two distinct elements.
    Assert: Use the Find function to verify that the two elements are in the same set after the Union operation.
Validation:
    The assertion is checking that the two elements belong to the same set after the Union operation, which is the expected behavior of the function. This test is important to ensure that the Union operation is correctly merging sets.

Scenario 2: Union of two elements in the same set

Details:
    Description: This test is meant to check the functionality of the Union operation when two elements that are already in the same set are passed. The function should return the UnionFind struct without any changes.
Execution:
    Arrange: Initialize a UnionFind struct and perform a Union operation on two elements.
    Act: Call the Union function on the same two elements.
    Assert: Use the Find function to verify that the two elements are still in the same set and no other changes have occurred.
Validation:
    The assertion is checking that the Union operation has not affected the sets when the two elements are already in the same set. This test is important to ensure that the Union operation is correctly handling this case and not causing any unnecessary changes.

Scenario 3: Union of two elements where one set is larger than the other

Details:
    Description: This test is meant to check the functionality of the Union operation when one set is larger than the other. The function should merge the two sets with the root of the larger set becoming the root of the merged set.
Execution:
    Arrange: Initialize a UnionFind struct and perform Union operations to create one larger set and one smaller set.
    Act: Call the Union function on an element from the larger set and an element from the smaller set.
    Assert: Use the Find function to verify that the root of the merged set is the root of the original larger set.
Validation:
    The assertion is checking that the Union operation is correctly merging the sets and choosing the root of the larger set as the root of the merged set. This test is important to ensure that the Union operation is correctly handling sets of different sizes.
*/

// ********RoostGPT********

package graph

import "testing"

func TestUnionFind_Union(t *testing.T) {
	tests := []struct {
		name       string
		initialUF  UnionFind
		unionPairs [][2]int
		findPairs  [][2]int
		expected   int
	}{
		{
			name: "Union of two distinct elements",
			initialUF: UnionFind{
				parent: []int{0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
				size:   []int{1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
			},
			unionPairs: [][2]int{{0, 1}},
			findPairs:  [][2]int{{0, 1}},
			expected:   1,
		},
		{
			name: "Union of two elements in the same set",
			initialUF: UnionFind{
				parent: []int{0, 0, 2, 2, 4, 4, 6, 6, 8, 8},
				size:   []int{2, 2, 2, 2, 2, 2, 2, 2, 2, 2},
			},
			unionPairs: [][2]int{{0, 1}},
			findPairs:  [][2]int{{0, 1}},
			expected:   0,
		},
		{
			name: "Union of two elements where one set is larger than the other",
			initialUF: UnionFind{
				parent: []int{0, 0, 0, 3, 4, 4, 6, 6, 8, 8},
				size:   []int{3, 3, 3, 1, 2, 2, 2, 2, 2, 2},
			},
			unionPairs: [][2]int{{0, 3}},
			findPairs:  [][2]int{{0, 3}},
			expected:   0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			for _, pair := range tt.unionPairs {
				tt.initialUF = tt.initialUF.Union(pair[0], pair[1])
			}
			for _, pair := range tt.findPairs {
				if got := tt.initialUF.Find(pair[0]); got != tt.expected {
					t.Errorf("UnionFind.Union() = %v, want %v", got, tt.expected)
				}
			}
		})
	}
}
