// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=NewUnionFind_8783c7dbf1
ROOST_METHOD_SIG_HASH=NewUnionFind_29f8a0beb9

FUNCTION_DEF=func NewUnionFind(s int) UnionFind
Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-samples/graph/unionfind_test.go
Test Cases:
    [TestUnionFind]

File: go-samples/graph/unionfind_unionfind.find_test.go
Test Cases:
    [TestFind]

File: go-samples/graph/unionfind_unionfind.union_test.go
Test Cases:
    [TestUnion]

Scenario 1: Testing NewUnionFind with a positive integer

Details:
    Description: This test is meant to check if the NewUnionFind function can correctly initialize a UnionFind structure with a positive integer as the size. The size of the UnionFind structure should match the input size, and all elements should be initialized correctly.
Execution:
    Arrange: No setup is required for this test.
    Act: Invoke the NewUnionFind function with a positive integer.
    Assert: Use Go testing facilities to verify that the size of the UnionFind structure matches the input size, and that all elements are initialized correctly.
Validation:
    The assertion checks that the size of the UnionFind structure is correct and that all elements are initialized correctly. This is important to ensure that the UnionFind structure is set up correctly for further operations.

Scenario 2: Testing NewUnionFind with zero

Details:
    Description: This test is meant to check if the NewUnionFind function can correctly handle an input of zero. The size of the UnionFind structure should be zero, and no elements should be initialized.
Execution:
    Arrange: No setup is required for this test.
    Act: Invoke the NewUnionFind function with zero.
    Assert: Use Go testing facilities to verify that the size of the UnionFind structure is zero, and that no elements are initialized.
Validation:
    The assertion checks that the size of the UnionFind structure is zero and that no elements are initialized. This is important to ensure that the UnionFind structure can handle an input of zero correctly.

Scenario 3: Testing NewUnionFind with a negative integer

Details:
    Description: This test is meant to check if the NewUnionFind function can correctly handle a negative integer. The function should return an error when a negative integer is passed as the size.
Execution:
    Arrange: No setup is required for this test.
    Act: Invoke the NewUnionFind function with a negative integer.
    Assert: Use Go testing facilities to verify that the function returns an error.
Validation:
    The assertion checks that the function returns an error when a negative integer is passed as the size. This is important to ensure that the function can handle invalid inputs correctly.
*/

// ********RoostGPT********

package graph

func equalUnionFind(a, b UnionFind) bool {
	if len(a.parent) != len(b.parent) || len(a.size) != len(b.size) {
		return false
	}
	for i := range a.parent {
		if a.parent[i] != b.parent[i] || a.size[i] != b.size[i] {
			return false
		}
	}
	return true
}
