// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=Abs_59856b4121
ROOST_METHOD_SIG_HASH=Abs_cc063e13ad

FUNCTION_DEF=func Abs(n int) int // Abs returns absolute value

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-samples/math/abs_test.go
Test Cases:
    [TestAbs]

Scenario 1: Positive Integer Input

Details:
    Description: This test is meant to check if the function correctly returns the absolute value of a positive integer. The target scenario is when the function is given a positive integer as input.
Execution:
    Arrange: No setup is required as the function takes a single integer as input.
    Act: Invoke the Abs function with a positive integer.
    Assert: Use Go testing facilities to verify that the actual result matches the input.
Validation:
    The assertion checks if the function returns the same value as the input when given a positive integer. This is important as it verifies the function's correct behavior when handling positive integers.

Scenario 2: Negative Integer Input

Details:
    Description: This test is meant to check if the function correctly returns the absolute value of a negative integer. The target scenario is when the function is given a negative integer as input.
Execution:
    Arrange: No setup is required as the function takes a single integer as input.
    Act: Invoke the Abs function with a negative integer.
    Assert: Use Go testing facilities to verify that the actual result matches the positive equivalent of the input.
Validation:
    The assertion checks if the function returns the positive equivalent of the input when given a negative integer. This is important as it verifies the function's correct behavior when handling negative integers.

Scenario 3: Zero Input

Details:
    Description: This test is meant to check if the function correctly returns zero when given zero as input. The target scenario is when the function is given zero as input.
Execution:
    Arrange: No setup is required as the function takes a single integer as input.
    Act: Invoke the Abs function with zero.
    Assert: Use Go testing facilities to verify that the actual result is zero.
Validation:
    The assertion checks if the function returns zero when given zero as input. This is important as it verifies the function's correct behavior when handling zero.
*/

// ********RoostGPT********

package math_test

import "testing"

func Abs(n int) int {
	if n < 0 {
		return -n
	}
	return n
}
func TestAbs(t *testing.T) {
	tests := []struct {
		name string
		n    int
		want int
	}{
		{
			name: "Positive Integer Input",
			n:    5,
			want: 5,
		},
		{
			name: "Negative Integer Input",
			n:    -3,
			want: 3,
		},
		{
			name: "Zero Input",
			n:    0,
			want: 0,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := Abs(test.n); got != test.want {
				t.Errorf("Abs() = %v, want %v", got, test.want)
			}
		})
	}
}
