// ********RoostGPT********
/*
Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test go-samples-1 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=Phi_24a5aef0f1
ROOST_METHOD_SIG_HASH=Phi_9b193ada7d

FUNCTION_DEF=func Phi(n int64) int64 // Phi is the Euler totient function.
// This function computes the number of numbers less then n that are coprime with n.

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-samples/math/eulertotient_test.go
Test Cases:
    [TestPhi]

Scenario 1: Testing with a prime number

Details:
    Description: This test is meant to check the functionality of the Phi function when a prime number is passed as an argument. Since prime numbers are only divisible by 1 and themselves, the function should return 1 less than the input number.
Execution:
    Arrange: No setup required.
    Act: Invoke the Phi function with a prime number (e.g., 7).
    Assert: Use Go testing facilities to verify that the returned result is 1 less than the input number (e.g., 6).
Validation:
    The assertion checks if the function correctly calculates the number of numbers less than the input number that are coprime with the input number. This test is important as it checks the basic functionality of the Phi function with prime numbers.

Scenario 2: Testing with a non-prime number

Details:
    Description: This test is meant to check the functionality of the Phi function when a non-prime number is passed as an argument. The function should return the count of numbers less than the input number that are coprime with the input number.
Execution:
    Arrange: No setup required.
    Act: Invoke the Phi function with a non-prime number (e.g., 8).
    Assert: Use Go testing facilities to verify that the returned result is the count of numbers less than the input number that are coprime with the input number.
Validation:
    The assertion checks if the function correctly calculates the number of numbers less than the input number that are coprime with the input number. This test is important as it checks the basic functionality of the Phi function with non-prime numbers.

Scenario 3: Testing with a negative number

Details:
    Description: This test is meant to check the functionality of the Phi function when a negative number is passed as an argument. Since the function is not defined for negative numbers, it should return 0.
Execution:
    Arrange: No setup required.
    Act: Invoke the Phi function with a negative number (e.g., -5).
    Assert: Use Go testing facilities to verify that the returned result is 0.
Validation:
    The assertion checks if the function correctly handles negative numbers. This test is important as it checks the error handling capability of the Phi function.

Scenario 4: Testing with zero

Details:
    Description: This test is meant to check the functionality of the Phi function when zero is passed as an argument. Since the function is not defined for zero, it should return 0.
Execution:
    Arrange: No setup required.
    Act: Invoke the Phi function with zero.
    Assert: Use Go testing facilities to verify that the returned result is 0.
Validation:
    The assertion checks if the function correctly handles zero. This test is important as it checks the error handling capability of the Phi function.
*/

// ********RoostGPT********

package math_test

import "testing"

func Phi(n int64) int64 {
	result := n
	for i := int64(2); i*i <= n; i += 1 {
		if n%i == 0 {
			for {
				if n%i != 0 {
					break
				}
				n /= i
			}
			result -= result / i
		}
	}
	if n > 1 {
		result -= result / n
	}
	return result
}
func TestPhi(t *testing.T) {
	tests := []struct {
		name     string
		input    int64
		expected int64
	}{
		{
			name:     "Testing with a prime number",
			input:    7,
			expected: 6,
		},
		{
			name:     "Testing with a non-prime number",
			input:    8,
			expected: 4,
		},
		{
			name:     "Testing with a negative number",
			input:    -5,
			expected: 0,
		},
		{
			name:     "Testing with zero",
			input:    0,
			expected: 0,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := Phi(test.input)
			if result != test.expected {
				t.Errorf("Wrong result! Expected:%v, returned:%v ", test.expected, result)
			}
		})
	}
}
