// ********RoostGPT********
/*
Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview

ROOST_METHOD_HASH=isSorted_fa5110ab18
ROOST_METHOD_SIG_HASH=isSorted_ef8018aa66

FUNCTION_DEF=func isSorted[T constraints.Number](arr []T) bool 
Scenario 1: Array with Integers in Sorted Order

Details:
  Description: This test checks if the function correctly identifies a sorted array of integers.
Execution:
  Arrange: Create an array of integers that are in ascending order.
  Act: Invoke `isSorted` passing the sorted array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion validates that the function correctly identifies a sorted array. This test is important as it checks the function's ability to recognize the correct ordering of elements according to the array's intended behavior.

Scenario 2: Array with Integers in Unsorted Order

Details:
  Description: This test checks if the function correctly identifies an unsorted array of integers.
Execution:
  Arrange: Create an array of integers that is not in ascending order.
  Act: Invoke `isSorted` passing the unsorted array.
  Assert: Use Go testing facilities to verify that the function returns `false`.
Validation:
  The assertion validates that the function correctly identifies an unsorted array. This test is crucial for ensuring the function can detect when elements are out of order, which is its primary purpose.

Scenario 3: Empty Array

Details:
  Description: This test checks if the function handles an empty array correctly.
Execution:
  Arrange: Create an empty array of integers.
  Act: Invoke `isSorted` passing the empty array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion checks that the function treats an empty array as sorted, which is a valid assumption since there are no elements to be out of order. This test is significant because it verifies the function's behavior in edge cases with no elements.

Scenario 4: Array with One Element

Details:
  Description: This test checks if the function handles an array with only one element correctly.
Execution:
  Arrange: Create an array of integers with a single element.
  Act: Invoke `isSorted` passing the one-element array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion checks that the function treats an array with one element as sorted. This test is important because it verifies the function's behavior with the smallest non-empty array.

Scenario 5: Array with Floating Point Numbers in Sorted Order

Details:
  Description: This test checks if the function correctly identifies a sorted array of floating-point numbers.
Execution:
  Arrange: Create an array of floating-point numbers that are in ascending order.
  Act: Invoke `isSorted` passing the sorted array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion validates that the function can handle floating-point numbers and correctly identifies when they are sorted. This test is essential for validating the function's generic type handling capabilities.

Scenario 6: Array with Negative Integers

Details:
  Description: This test checks if the function correctly identifies a sorted array containing negative integers.
Execution:
  Arrange: Create an array of negative integers that are in ascending order.
  Act: Invoke `isSorted` passing the sorted array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion ensures that the function can handle negative numbers and correctly identifies their order. This test is significant because it tests the function's behavior with negative values, which could be a potential edge case.

Scenario 7: Large Array with Random Integers

Details:
  Description: This test checks if the function correctly identifies the order of a large array with random integers.
Execution:
  Arrange: Create a large array with random integers and sort it.
  Act: Invoke `isSorted` passing the sorted array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion validates that the function can handle large datasets. This test is important to ensure that the function performs correctly with a realistic dataset that could be encountered in production.

Scenario 8: Array with Duplicate Elements in Sorted Order

Details:
  Description: This test checks if the function correctly identifies a sorted array with duplicate elements.
Execution:
  Arrange: Create an array of integers with duplicate elements that are in ascending order.
  Act: Invoke `isSorted` passing the sorted array.
  Assert: Use Go testing facilities to verify that the function returns `true`.
Validation:
  The assertion ensures that the function treats arrays with duplicate elements as sorted if they are in non-descending order. This test is important because it validates that the function's behavior is correct when there are equal elements adjacent to each other.
*/

// ********RoostGPT********


package github.com/TheAlgorithms/Go/sort

import (
	"math/rand"
	"testing"
	"github.com/TheAlgorithms/Go/constraints"
)







func TestIsSorted(t *testing.T) {

	testCases := []struct {
		name     string
		input    []constraints.Number
		expected bool
	}{
		{
			name:     "Array with Integers in Sorted Order",
			input:    []constraints.Number{1, 2, 3, 4, 5},
			expected: true,
		},
		{
			name:     "Array with Integers in Unsorted Order",
			input:    []constraints.Number{5, 3, 1, 2, 4},
			expected: false,
		},
		{
			name:     "Empty Array",
			input:    []constraints.Number{},
			expected: true,
		},
		{
			name:     "Array with One Element",
			input:    []constraints.Number{1},
			expected: true,
		},
		{
			name:     "Array with Floating Point Numbers in Sorted Order",
			input:    []constraints.Number{1.1, 2.2, 3.3, 4.4, 5.5},
			expected: true,
		},
		{
			name:     "Array with Negative Integers",
			input:    []constraints.Number{-5, -4, -3, -2, -1},
			expected: true,
		},
		{
			name:     "Large Array with Random Integers",
			input:    generateSortedRandomInts(1000),
			expected: true,
		},
		{
			name:     "Array with Duplicate Elements in Sorted Order",
			input:    []constraints.Number{1, 2, 2, 3, 4, 4, 5},
			expected: true,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Log("Scenario:", tc.name)
			result := isSorted(tc.input)
			if result != tc.expected {
				t.Errorf("Expected %v, got %v", tc.expected, result)
			} else {
				t.Logf("Success: array %v is correctly identified as sorted: %v", tc.input, result)
			}
		})
	}
}
func generateSortedRandomInts(size int) []constraints.Number {
	arr := make([]constraints.Number, size)
	for i := range arr {
		arr[i] = constraints.Number(rand.Intn(1000))
	}

	for i := 1; i < len(arr); i++ {
		for j := i; j > 0 && arr[j-1] > arr[j]; j-- {
			arr[j], arr[j-1] = arr[j-1], arr[j]
		}
	}
	return arr
}
